apiVersion: v1
kind: Service
metadata:
  name: { { .Values.fullnameOverride | default "mongodb" } }
  labels:
    app: { { .Values.fullnameOverride | default "mongodb" } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.port } }
      protocol: TCP
      name: mongodb
  selector:
    app: { { .Values.fullnameOverride | default "mongodb" } }
