apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "mongodb.fullname" .) }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 27017 }}
      targetPort: {{ .Values.service.port | default 27017 }}
      protocol: TCP
      name: mongodb
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}
