apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: {{ .Values.service.port | default 27017 }}
      targetPort: mongodb
      protocol: TCP
