apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: server
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: server
  namespaceSelector:
    matchNames:
      - project-manager
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
