apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.fullnameOverride | default "client" } }
  labels:
    app: { { .Values.fullnameOverride | default "client" } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { .Values.fullnameOverride | default "client" } }
  template:
    metadata:
      labels:
        app: { { .Values.fullnameOverride | default "client" } }
    spec:
      containers:
        - name: client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - containerPort: { { .Values.service.port } }
              name: http
          env:
            - name: REACT_APP_SERVER_URL
              value: { { .Values.env.serverUrl | quote } }
            - name: API_URL
              value: { { .Values.env.serverUrl | quote } }
          resources: { { - toYaml .Values.resources | nindent 10 } }
