apiVersion: v1
kind: Service
metadata:
  name: { { include "client.fullname" . } }
  labels: { { - include "client.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type | default "ClusterIP" } }
  ports:
    - name: http
      port: { { .Values.service.port | default 3000 } }
      targetPort: http
      protocol: TCP
  selector: { { - include "client.selectorLabels" . | nindent 4 } }
