apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: client
  ports:
    - name: http
      port: {{ .Values.service.port | default 5173 }}
      targetPort: http
      protocol: TCP
