replicaCount: 1

image:
  repository: daliii/project-manager-backend
  tag: "1.0.3"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

env:
  dbUrl: "mongodb://mongodb:27017/project_manager"
  mongoUri: "mongodb://mongodb:27017/project_manager"
  port: "5000"
