apiVersion: v1
kind: Service
metadata:
  name: { { include "server.fullname" . } }
  labels: { { - include "server.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type | default "ClusterIP" } }
  ports:
    - name: http
      port: { { .Values.service.port | default 5000 } }
      targetPort: http
      protocol: TCP
  selector: { { - include "server.selectorLabels" . | nindent 4 } }
