replicaCount: 1

image:
  repository: daliii/project-manager-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5173
containerPort: 5173

env:
  serverUrl: "http://server:5000"

ingress:
  enabled: false
  className: ""
  annotations: {}
  host: mern-app.local
  path: /
  pathType: Prefix
