replicaCount: 1

image:
  repository: daliii/project-manager-frontend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

env:
  serverUrl: "http://server:5000"
  # Pour React: REACT_APP_SERVER_URL
  # Pour Angular: API_URL

ingress:
  enabled: true
  className: ""
  host: mern-app.local
  path: /
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nameOverride: "client"
fullnameOverride: "client"
